version: '3'

services:
  database:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "Postgres2021!"
      POSTGRES_DB: "contacts"
    ports:
      - "5432:5432"
    volumes:
      - ./Database/create.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - app-network

  backend:
    #    image: tonnytg/catalogapi:version1.0
    build:
      context: Backend
    container_name: backend
    restart: always
    tty: true
    networks:
      - app-network
    ports:
      - "3000:3000"
    depends_on:
      - "database"
      - "rabbitmq"

networks:
  app-network:
    driver: bridge
